### ISSUE TITLE
Example App Throws Server Error

### ISSUE THREAD

**Issue by paddycarver** [iron-io/heroku_sinatra_example#1]
http://evening-planet-3202.herokuapp.com is throwing an "Internal Server Error" at the moment.

**Comment by treeder** [comment]
Ok, should work now. Needed a gem update.

On Fri, Jan 6, 2012 at 2:53 PM, Paddy Foran <
reply@reply.github.com

**Comment by thousandsofthem** [comment]
```
Internal Server Error
can't convert nil into String
```

http://evening-planet-3202.herokuapp.com still throwing an error.

**Comment by treeder** [comment]
Delete your cookies, that error has something to do with session cookies,
no idea why.

On Sat, Jan 7, 2012 at 2:23 PM, Alexander Shapiotko <
reply@reply.github.com

**Comment by thousandsofthem** [comment]
Yeah, removing cookies fixes the issue. Thanks!
